// AUTO-GENERATED by props/tools/generate_style_schema.py. DO NOT EDIT.
#ifndef PROPS_GENERATED_STYLE_SCHEMA_H
#define PROPS_GENERATED_STYLE_SCHEMA_H

#include <cstring>

struct GeneratedParamDef {
  const char* style_name;
  const char* key;
  const char* arg_symbol;
};

struct GeneratedStyleDef {
  const char* name;
  const char* core_type;
  const char* parser_name;
  int param_offset;
  int param_count;
};

static constexpr int kGeneratedStyleSchemaVersion = 1;

static const GeneratedParamDef kGeneratedParamDefs[] = {
  {"standard", "base_color", "BASE_COLOR_ARG"},
  {"standard", "alt_color", "ALT_COLOR_ARG"},
  {"standard", "style_option", "STYLE_OPTION_ARG"},
  {"standard", "ignition_option", "IGNITION_OPTION_ARG"},
  {"standard", "ignition_time", "IGNITION_TIME_ARG"},
  {"standard", "ignition_delay", "IGNITION_DELAY_ARG"},
  {"standard", "ignition_color", "IGNITION_COLOR_ARG"},
  {"standard", "ignition_power_up", "IGNITION_POWER_UP_ARG"},
  {"standard", "blast_color", "BLAST_COLOR_ARG"},
  {"standard", "clash_color", "CLASH_COLOR_ARG"},
  {"standard", "lockup_color", "LOCKUP_COLOR_ARG"},
  {"standard", "lockup_position", "LOCKUP_POSITION_ARG"},
  {"standard", "drag_color", "DRAG_COLOR_ARG"},
  {"standard", "drag_size", "DRAG_SIZE_ARG"},
  {"standard", "lb_color", "LB_COLOR_ARG"},
  {"standard", "stab_color", "STAB_COLOR_ARG"},
  {"standard", "melt_size", "MELT_SIZE_ARG"},
  {"standard", "swing_color", "SWING_COLOR_ARG"},
  {"standard", "swing_option", "SWING_OPTION_ARG"},
  {"standard", "emitter_color", "EMITTER_COLOR_ARG"},
  {"standard", "emitter_size", "EMITTER_SIZE_ARG"},
  {"standard", "preon_color", "PREON_COLOR_ARG"},
  {"standard", "preon_option", "PREON_OPTION_ARG"},
  {"standard", "preon_size", "PREON_SIZE_ARG"},
  {"standard", "retraction_option", "RETRACTION_OPTION_ARG"},
  {"standard", "retraction_time", "RETRACTION_TIME_ARG"},
  {"standard", "retraction_delay", "RETRACTION_DELAY_ARG"},
  {"standard", "retraction_color", "RETRACTION_COLOR_ARG"},
  {"standard", "retraction_cool_down", "RETRACTION_COOL_DOWN_ARG"},
  {"standard", "postoff_color", "POSTOFF_COLOR_ARG"},
  {"standard", "off_color", "OFF_COLOR_ARG"},
  {"standard", "off_option", "OFF_OPTION_ARG"},
  {"audioflicker", "base_color", "BASE_COLOR_ARG"},
  {"audioflicker", "alt_color", "ALT_COLOR_ARG"},
  {"audioflicker", "style_option", "STYLE_OPTION_ARG"},
  {"audioflicker", "ignition_option", "IGNITION_OPTION_ARG"},
  {"audioflicker", "ignition_time", "IGNITION_TIME_ARG"},
  {"audioflicker", "ignition_delay", "IGNITION_DELAY_ARG"},
  {"audioflicker", "ignition_color", "IGNITION_COLOR_ARG"},
  {"audioflicker", "ignition_power_up", "IGNITION_POWER_UP_ARG"},
  {"audioflicker", "blast_color", "BLAST_COLOR_ARG"},
  {"audioflicker", "clash_color", "CLASH_COLOR_ARG"},
  {"audioflicker", "lockup_color", "LOCKUP_COLOR_ARG"},
  {"audioflicker", "lockup_position", "LOCKUP_POSITION_ARG"},
  {"audioflicker", "drag_color", "DRAG_COLOR_ARG"},
  {"audioflicker", "drag_size", "DRAG_SIZE_ARG"},
  {"audioflicker", "lb_color", "LB_COLOR_ARG"},
  {"audioflicker", "stab_color", "STAB_COLOR_ARG"},
  {"audioflicker", "melt_size", "MELT_SIZE_ARG"},
  {"audioflicker", "swing_color", "SWING_COLOR_ARG"},
  {"audioflicker", "swing_option", "SWING_OPTION_ARG"},
  {"audioflicker", "emitter_color", "EMITTER_COLOR_ARG"},
  {"audioflicker", "emitter_size", "EMITTER_SIZE_ARG"},
  {"audioflicker", "preon_color", "PREON_COLOR_ARG"},
  {"audioflicker", "preon_option", "PREON_OPTION_ARG"},
  {"audioflicker", "preon_size", "PREON_SIZE_ARG"},
  {"audioflicker", "retraction_option", "RETRACTION_OPTION_ARG"},
  {"audioflicker", "retraction_time", "RETRACTION_TIME_ARG"},
  {"audioflicker", "retraction_delay", "RETRACTION_DELAY_ARG"},
  {"audioflicker", "retraction_color", "RETRACTION_COLOR_ARG"},
  {"audioflicker", "retraction_cool_down", "RETRACTION_COOL_DOWN_ARG"},
  {"audioflicker", "postoff_color", "POSTOFF_COLOR_ARG"},
  {"audioflicker", "off_color", "OFF_COLOR_ARG"},
  {"audioflicker", "off_option", "OFF_OPTION_ARG"},
  {"audioflicker", "alt_color2", "ALT_COLOR2_ARG"},
  {"audioflicker", "alt_color3", "ALT_COLOR3_ARG"},
  {"audioflicker", "style_option2", "STYLE_OPTION2_ARG"},
  {"audioflicker", "style_option3", "STYLE_OPTION3_ARG"},
  {"audioflicker", "ignition_option2", "IGNITION_OPTION2_ARG"},
  {"audioflicker", "retraction_option2", "RETRACTION_OPTION2_ARG"},
};

static constexpr int kGeneratedParamDefCount =
    static_cast<int>(sizeof(kGeneratedParamDefs) / sizeof(kGeneratedParamDefs[0]));

static const GeneratedStyleDef kGeneratedStyleDefs[] = {
  {"standard", "main", "ini2_standard", 0, 32},
  {"audioflicker", "main", "ini2_audioflicker", 32, 38},
};

static constexpr int kGeneratedStyleDefCount =
    static_cast<int>(sizeof(kGeneratedStyleDefs) / sizeof(kGeneratedStyleDefs[0]));

static inline const GeneratedStyleDef* FindGeneratedStyleDef(const char* style_name) {
  if (!style_name) {
    return nullptr;
  }
  for (int i = 0; i < kGeneratedStyleDefCount; ++i) {
    if (std::strcmp(style_name, kGeneratedStyleDefs[i].name) == 0) {
      return &kGeneratedStyleDefs[i];
    }
  }
  return nullptr;
}

#endif  // PROPS_GENERATED_STYLE_SCHEMA_H
